module.exports = {
  GET_ITEM_REQUEST: "GET_ITEM_REQUEST",
  GET_ITEM_SUCCESS: "GET_ITEM_SUCCESS",
  GET_ITEM_FAILURE: "GET_ITEM_FAILURE",
  GET_SALES_REQUEST: "GET_SALES_REQUEST",
  GET_SALES_SUCCESS: "GET_SALES_SUCCESS",
  GET_SALES_FAILURE: "GET_SALES_FAILURE",
  RESET_SALES: "RESET_SALES"
}